---
- name: Set MySQL root password before installing
  become: yes
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{ mysql_root_password }}' vtype='password'

- name: Confirm MySQL root password before installing
  become: yes
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{ mysql_root_password }}' vtype='password'

- name: Install MySQL
  become: yes
  apt: name="{{ item }}" state=latest update-cache=yes
  with_items:
      - mysql-server
      - mysql-client

- name: Update root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    check_implicit_admin: yes
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
  with_items:
    - "{{ hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Create MySQL users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "*.*:ALL,GRANT"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  with_items: "{{ mysql.users }}"

- name: Create MySQL databases
  mysql_db:
    name: "{{ item }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  with_items: "{{ mysql.databases }}"

- name: Delete anonymous MySQL user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: ""
    host: "{{ item }}"
    state: "absent"
  with_items:
    - "{{ hostname }}"
    - 127.0.0.1
    - localhost
    - ::1

- name: Remove the MySQL test database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: test
    state: absent
