---

- name: Give the permissions to the Laravel storage folder dir to www-data
  file: path=/var/www/{{ web_dirname }}/storage state=directory group="www-data" mode="ug+rwx"

- name: Give the permissions to the Laravel cache folder dir to www-data
  file: path=/var/www/{{ web_dirname }}/bootstrap/cache state=directory group="www-data" mode="ug+rwx"
